# Generated by Django 2.2.7 on 2019-11-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191123_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(default='en', max_length=6),
            preserve_default=False,
        ),
    ]
