# Generated by Django 2.2.7 on 2019-11-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_student_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='student_tags', to='api.Tag'),
        ),
    ]
