# Generated by Django 2.2.7 on 2019-11-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_student_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='student_tags', to='api.Tag'),
        ),
    ]
