# Generated by Django 2.2.7 on 2019-11-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191123_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='lang',
            field=models.CharField(default='fr', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialogstrings',
            name='lang',
            field=models.CharField(default='fr', max_length=50),
            preserve_default=False,
        ),
    ]
